export const ZK_CREDENTIAL_ID = process.env.NEXT_PUBLIC_ZK_CREDENTIAL_ID || "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2KM";
export const PRIVATE_GOVERNANCE_ID = process.env.NEXT_PUBLIC_PRIVATE_GOVERNANCE_ID || "CBJFN27YH2D5HGI5SOZYNYPJZ6W776QCSJSGVIMUZSCEDR52XXLMRSHG";
export const PRIVATE_TREASURY_ID = process.env.NEXT_PUBLIC_PRIVATE_TREASURY_ID || "CD6HGS5V7XJPSPJ5HHPHUZXLYGZAJJC3L6QWR4YZG4NIRO65UYQ6KIYP";

export const STELLAR_NETWORK = "TESTNET";
export const SOROBAN_RPC_URL = "https://soroban-testnet.stellar.org";
